import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { LoadingSpinner } from "~/components/loading";
import { api } from "~/utils/api";

const Home: NextPage = () => {

  const {data: courses, isLoading: coursesLoading} = api.course.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div className="container flex flex-col items-center justify-center gap-4 bg-slate-700 px-4 py-16 text-slate-200">
          {courses ? (courses.map((course) => {
            return (
              <Link key={course.id} href={`/course/${course.id}`}>{course.name}</Link>
            )
          })) : <LoadingSpinner/>}
        </div>
      </main>
    </>
  );
}

export default Home;
