import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { LoadingSpinner } from "~/components/loading";
import { api } from "~/utils/api";

const CoursePage: NextPage = () => {
  const router = useRouter();
  const {
    query: { id },
  } = router;

  if (!id) {
    return <div>404</div>;
  }

  const courseId = id as string;
  const { data: course, isLoading: coursesLoading } =
    api.course.getById.useQuery({ id: courseId });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-800">
        <div className="container flex flex-col items-center justify-center gap-4 bg-slate-700 px-4 py-16 text-slate-200">
          {course ? (
            <div>
              <div className="text-center">{course.name}</div>
              <table className="min-w-full border-collapse">
                <thead>
                  <tr>
                    <td>Hole</td>
                    {course?.holes.map((hole, index) => (
                      <th className="w-auto border p-2" key={index}>
                        {hole.number}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>Par</td>
                    {course?.holes.map((hole, index) => (
                      <td className="w-auto border p-2" key={index}>
                        {hole.par}
                      </td>
                    ))}
                  </tr>
                  <tr>
                    <td>Handicap</td>
                    {course?.holes.map((hole, index) => (
                      <td className="w-auto border p-2" key={index}>
                        {hole.handicap}
                      </td>
                    ))}
                  </tr>
                </tbody>
              </table>
            </div>
          ) : (
            <LoadingSpinner />
          )}
        </div>
      </main>
    </>
  );
};

export default CoursePage;
